INSERT INTO products (
  name,
  brand,
  category,
  skin_use_case,
  why_relevant,
  inci_available,
  inci_source_url,
  product_source_url,
  source_type,
  ingredients,
  notes
)
VALUES
  (
    'Renewing SA Cleanser',
    'CeraVe',
    'cleanser',
    ARRAY['acne-prone', 'oily', 'sensitive'],
    'Sredstvo za čišćenje koje kombinira salicilnu kiselinu (BHA) za blagu kemijsku eksfolijaciju i otapanje komedona bez grubih abrazivnih čestica. Jedinstvenost leži u kompenzacijskom kompleksu (tri esencijalna ceramida NP, AP, EOP, hijaluronska kiselina i niacinamid) koji štiti epidermalnu barijeru od isušivanja tijekom pranja.',
    true,
    'https://www.cerave.com/skincare/cleansers/renewing-sa-cleanser',
    'https://www.cerave.com/skincare/cleansers/renewing-sa-cleanser',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Puni INCI sastav dostupan je i dokumentiran, formula je nekomedogena, bez mirisa i alergološki testirana, što je čini pogodnom za iznimno osjetljivu kožu sklonu aknama.')
  ),
  (
    'Effaclar Duo+M',
    'La Roche-Posay',
    'acne treatment',
    ARRAY['acne-prone', 'oily'],
    'Centralni korektivni tretman LRP-a. Integrira mikrobiomsku znanost putem postbiotika Vitreoscilla Ferment za inhibiciju proliferacije C. acnes. Niacinamid i Cink PCA djeluju protuupalno i seboregulacijski, dok salicilna kiselina i LHA (lipo-hidroksi kiselina) vrše mikroljuštenje začepljenih pora bez drastičnog ljuštenja stratum corneuma.',
    true,
    'https://incidecoder.com/products/la-roche-posay-effaclar-duo-m',
    'https://africa.laroche-posay.com/en-za/effaclar/effaclar-duo-plus-m-anti-imperfections-triple-corrective-care',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Puni INCI sastav potvrđen u službenim globalnim bazama i neovisnim INCI analizatorima.')
  ),
  (
    'Sun Face Oil Control Gel-Cream SPF 50+',
    'Eucerin',
    'sunscreen',
    ARRAY['acne-prone', 'oily', 'sensitive'],
    'Ovaj proizvod nadilazi samu fotoprotekciju djelujući kao aktivni tretman. Koristi inovativnu tehnologiju kontrole ulja s L-Karnitinom za dokazano smanjenje sebuma i 14-satni mat učinak. Sadrži Licochalcone A, ekstrakt sladića koji pruža biološku staničnu zaštitu neutralizacijom slobodnih radikala.',
    true,
    'https://int.eucerin.com/products/sun-protection/sun-gel-creme-dry-touch-spf-50plus#pdp-ingredients-section',
    'https://int.eucerin.com/products/sun-protection/sun-gel-creme-dry-touch-spf-50plus',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Formula je oslobođena kontroverznog filtera Octocrylene, nekomedogena je i prikladna kao baza za šminku bez stvaranja grudica (pilling efekta).')
  ),
  (
    'Cicalfate+ Restorative Protective Cream',
    'Avène',
    'moisturizer',
    ARRAY['barrier-impaired', 'sensitive'],
    'Dermatološki standard za zbrinjavanje kompromitirane kože, iritacija i oštećenja nakon tretmana. Bazira se na patentiranom postbiotiku C+-Restore™ deriviranom iz termalne vode koji ubrzava obnovu epitela za 48 sati, uz bakar-cink sulfat kompleks za održavanje sterilnog mikrookruženja.',
    true,
    'https://www.aveneusa.com/cicalfateplus-restorative-protective-cream',
    'https://www.aveneusa.com/cicalfateplus-restorative-protective-cream',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Formulacija je potpuno oslobođena mirisa, parabena, silikona i alkohola, s potvrđenom pedijatrijskom i onkološkom tolerancijom.')
  ),
  (
    'Bariéderm-Cica Daily Serum',
    'Uriage',
    'serum',
    ARRAY['barrier-impaired', 'sensitive'],
    'Specifičan rebalansirajući serum visoke tolerancije. Snaži kožu oštećenu vanjskim agresorima pomoću 10.5% Thermal-Biotic kompleksa (izotonična termalna voda + inulin), Centelle Asiatice za zacjeljivanje i vitamina B5, u izrazito fluidnoj teksturi.',
    true,
    'https://www.uriage.com/AA/en/products/bariederm-cica-daily-serum',
    'https://www.uriage.com/AA/en/products/bariederm-cica-daily-serum',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Sadrži dipeptide za prevenciju starenja kože, 96% sastojaka prirodnog je podrijetla. Pakirano u staklenu kapaljku.')
  ),
  (
    'Atoderm Intensive Baume',
    'Bioderma',
    'moisturizer',
    ARRAY['barrier-impaired', 'sensitive'],
    'Lipido-obnavljajući balzam ultimativne snage za atopijsku i suhu kožu. Kompleks Lipigenium™ (ceramidi, kolesterol, fitosfingozin) trajno obnavlja barijeru, dok PEA molekula biološki inhibira putanje koje uzrokuju svrbež, osiguravajući trenutačno i dugotrajno olakšanje.',
    true,
    'https://www.bioderma.sa/our-products/atoderm/intensive-baume',
    'https://www.bioderma.us/en/p/atoderm-intensive-balm.html',
    'official',
    '[]'::jsonb,
    jsonb_build_array('INCI lista potvrđena; formula koristi Skin Barrier Therapy tehnologiju koja ograničava adheziju zlatnog stafilokoka.')
  ),
  (
    'Ampoule Hydra',
    'SVR',
    'serum',
    ARRAY['sensitive', 'barrier-impaired', 'acne-prone'],
    'Koncentrirani "booster" serum baziran na impresivnih 5% niacinamida i kombinaciji tri različite molekularne mase hijaluronske kiseline. Istovremeno popravlja kožnu barijeru, suzbija upalne procese (ključno za akne i rozaceju) i osigurava multi-razinsku hidrataciju stanica.',
    true,
    'https://incidecoder.com/products/svr-b3-hydra-ampoule',
    'https://us.svr.com/products/ampoule-b3-hydra',
    'other',
    '[]'::jsonb,
    jsonb_build_array('Tekstura gela prilagođena je integraciji u svaku rutinu, INCI verificiran putem nezavisnih baza podataka i farmaceutskih distributera.')
  ),
  (
    'Moisturizing Cream',
    'CeraVe',
    'moisturizer',
    ARRAY['barrier-impaired', 'sensitive'],
    'Jedan od najpropisivanijih emolijensa u dermatologiji. Koristi okluzivna svojstva petrolatuma u sprezi s hijaluronskom kiselinom i tri esencijalna ceramida, uz patentiranu MVE tehnologiju za kontinuirano otpuštanje. Izvrsno za kompenzaciju isušivanja uslijed tretmana izotretinoinom.',
    true,
    'https://www.ewg.org/skindeep/products/1060240-CeraVe_Moisturising_Cream_/',
    'https://www.cerave.com/skincare/moisturizers/moisturizing-cream',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Ne-komedogena formula, dokazana sigurnost i stabilnost kroz EWG i službene izvore.')
  ),
  (
    'DermoPure Mattifying Fluid',
    'Eucerin',
    'moisturizer',
    ARRAY['acne-prone', 'oily'],
    'Treći korak u tretmanu masne kože – aktivna hidratacija i matiranje. Sadrži salicilnu kiselinu za komedolitički učinak, umirujući Licochalcone A i tehnologiju regulacije sebuma, omogućavajući 8 sati matiranog izgleda bez iritacija.',
    true,
    'https://incidecoder.com/products/eucerin-dermopure-clinical-mat-fluid',
    'https://skinsort.com/products/eucerin/dermopure-oil-control-mattifying-fluid',
    'other',
    '[]'::jsonb,
    jsonb_build_array('INCI potvrđen kroz SkinSort i InciDecoder analizatore zbog limitiranih INCI podataka na službenim američkim pod-domenama.')
  ),
  (
    'Cicaplast Balm B5',
    'La Roche-Posay',
    'moisturizer',
    ARRAY['barrier-impaired', 'sensitive'],
    'Kultni obnavljajući balzam "zlatni standard" za iritacije, ispucalost i njegu ožiljaka. Formula s 5% Pantenola (umirenje epitela), Madecassoside ekstraktom (ubrzanje epidermalne popravke) i Tribioma prebiotikom izolira i štiti kožu uz visoku toleranciju.',
    true,
    'https://www.laroche-posay.us/our-products/body/body-lotion/cicaplast-balm-b5-for-dry-skin-irritations-cicaplastbalmb5.html',
    'https://www.laroche-posay.us/our-products/body/body-lotion/cicaplast-balm-b5-for-dry-skin-irritations-cicaplastbalmb5.html',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Američko tržište klasificira ga i kao "Skin Protectant" s 1% Dimethiconea kao aktivnim FDA klasificiranim sastojkom. Puni INCI javan.')
  ),
  (
    'Cleanance Comedomed',
    'Avène',
    'acne treatment',
    ARRAY['acne-prone', 'oily'],
    'Revolucionarni koncentrat čiji se mehanizam oslanja na 25% Comedoclastin™ (ekstrakt sjemenki mliječnog čička). Cilja na sam korijen akni – mikrokomedone, prevenirajući njihov razvoj u papule i pustule. Ima ultra-brzu apsorpciju i klinički sprječava recidive do 1 godine.',
    true,
    'https://lyskin.com/shop/avene-cleanance-comedomed-anti-blemishes-concentrate-30ml/',
    'https://incidecoder.com/products/avene-cleanance-comedomed-anti-blemish-concentrate',
    'other',
    '[]'::jsonb,
    jsonb_build_array('Sadrži visok udio izopropilnog alkohola kao otapala za aktivnu tvar, što zahtijeva oprez kod iznimno dehidrirane kože.')
  ),
  (
    'Sébium Serum',
    'Bioderma',
    'serum',
    ARRAY['acne-prone', 'oily'],
    'Namijenjeno primarno aknama u odrasloj dobi (adult acne). Formula visoke tehnologije kombinira salicilnu kiselinu (keratolitik) s acetil-glukozaminom (derivatom hijalurona) za stimulaciju stanične obnove, gladeći prve bore uz istovremeno neutraliziranje mrlja.',
    true,
    'https://www.bioderma.ie/our-products/sebium/serum',
    'https://www.bioderma.co.uk/our-products/sebium/serum',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Potvrđen i dokumentiran INCI na više službenih platformi EU tržišta. Sadrži inovativnu aminokiselinsku tehnologiju za anti-aging i aknast ten.')
  ),
  (
    'Anthelios Oil Correct SPF 50+',
    'La Roche-Posay',
    'sunscreen',
    ARRAY['acne-prone', 'oily'],
    'Hibridni proizvod fotoprotekcije i tretmana. Oslanja se na CELLOX-B3 TECH s Mexoryl XL filterima za UV i anti-polucijsku zaštitu. Obogaćeno salicilnom kiselinom (odčepljivanje pora), cinkom (sebo-regulacija) i niacinamidom za spriječavanje post-upalnih pigmentacija potaknutih suncem.',
    true,
    'https://incidecoder.com/products/la-roche-posay-anthelios-oil-correct-spf-50',
    'https://www.laroche-posay.com.my/en-my/anthelios/anthelios-oil-correct',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Službeni podaci podržani neovisnim INCI pregledom. Tekstura gel-kreme stvara nevidljivi, ne-masni film na licu.')
  ),
  (
    'Hydrating Toner',
    'CeraVe',
    'toner',
    ARRAY['sensitive', 'barrier-impaired'],
    'Promjena paradigme u toniranju lica; proizvod bez alkohola i adstrigensa. Formulan da nakon umivanja trenutačno nadoknadi vlagu koristeći humektante, umiri kožu niacinamidom i sanira mikroskopska oštećenja barijere s 3 esencijalna ceramida.',
    true,
    'https://medrockpharmacy.com/product/cerave-hydrating-toner-for-face-non-alcoholic-with-hyaluronic-acid-niacinamide-and-ceramides-for-sensitive-dry-skin-fragrance/',
    'https://skinsort.com/products/cerave/hydrating-toner',
    'retailer',
    '[]'::jsonb,
    jsonb_build_array('Prikupljeni podaci temelje se na stručnim i maloprodajnim ljekarničkim bazama; proizvod ima potvrđen, siguran INCI za osjetljivu kožu.')
  ),
  (
    'UreaRepair Plus Cream 30% Urea',
    'Eucerin',
    'moisturizer',
    ARRAY['barrier-impaired'],
    'Specijalizirani tretmanski emolijens za najtvrdokornije, zadebljale oblike kseroze. Visoka koncentracija od 30% uree pruža ekstremni keratolitički učinak, otapajući epidermalne naslage, dok ceramidi istovremeno repariraju oštećeni matriks.',
    true,
    'https://incidecoder.com/products/eucerin-urearepair-plus-cream-30-urea',
    'https://int.eucerin.com/products/urea-repair',
    'other',
    '[]'::jsonb,
    jsonb_build_array('Namjenski proizvod. Nije opće namjene za cijelo lice nego za lokalizirane regije (laktovi, koljena, zadebljali plakovi). Puni INCI dostupan.')
  ),
  (
    'Tolerance Control Soothing Skin Recovery Cream',
    'Avène',
    'moisturizer',
    ARRAY['sensitive', 'barrier-impaired'],
    'Vrhunac minimalističke formulacije za alergijama i iritacijama sklonu kožu. Ključni sastojak D-Sensinose™ postbiotik promptno djeluje na senzorne živčane puteve za prekidanje kaskade koja uzrokuje osjećaj žarenja i zatezanja epitela.',
    true,
    'https://www.eau-thermale-avene.ca/en_ca/p/tolerance-control-restorative-soothing-cream-sterile-cosmetics-r-3282770138801-69716462',
    'https://www.aveneusa.com/tolerance-control-cream',
    'official',
    '[]'::jsonb,
    jsonb_build_array('INCI je izrazito kratak i jednostavan. Proizvedeno pod strogim pravilima sterilne kozmetike bez dodataka konzervansa.')
  ),
  (
    'Sebiaclear Active Gel',
    'SVR',
    'acne treatment',
    ARRAY['acne-prone', 'oily'],
    'Agresivno ciljanje akni uz poštivanje osjetljivosti kože. Kombinacija visokih koncentracija glukonolaktona (vrlo podnošljiva PHA kiselina s moćnim eksfolirajućim svojstvima) i salicilne kiseline (BHA) s niacinamidom, pruža učinak ravan propisanim lijekovima bez ljuštenja.',
    true,
    'https://incidecoder.com/products/svr-sebiaclear-active-gel',
    'https://us.svr.com/products/sebiaclear-essentials-kit',
    'other',
    '[]'::jsonb,
    jsonb_build_array('Formula obuhvaća kompleks za pročišćavanje. INCI detaljno razložen i provjeren u bazama sastojaka.')
  ),
  (
    'Xémose Lipid-Replenishing Cream',
    'Uriage',
    'moisturizer',
    ARRAY['barrier-impaired', 'sensitive'],
    'Ultimativni lipido-obnavljajući balzam za pruritičku kožu i atopijski dermatitis. Oslanja se na Uriage termalnu vodu, Cerasterol 2F i specifični Chronoxine kompleks koji momentalno deeskalira reflekse svrbeža i ojačava barijeru.',
    true,
    'https://uriage.ca/products/xemose-lipid-replenishing-cream',
    'https://www.uriage.com/MT/en/products/xemose-creme-visage',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Potvrđen složen sustav ceramida (NP, NS, EOP, AP) unutar INCI liste na službenoj kanadskoj i globalnoj domeni.')
  ),
  (
    'Effaclar Clarifying Solution Acne Toner',
    'La Roche-Posay',
    'toner',
    ARRAY['acne-prone', 'oily'],
    'Tretmanski tonik na bazi kiselina. Obogaćen s 0.5% salicilne kiseline (BHA) za lipofilno čišćenje pora i 2% glikolne kiseline (AHA) za glađenje površine rožnatog sloja, čime se komplementira primarni tretman za akne i ujednačava tekstura.',
    true,
    'https://www.laroche-posay.us/our-products/face/acne-products/effaclar-clarifying-solution-acne-toner-883140040248.html',
    'https://www.laroche-posay.us/our-products/face/acne-products/effaclar-clarifying-solution-acne-toner-883140040248.html',
    'official',
    '[]'::jsonb,
    jsonb_build_array('Napomena u vezi sastava: Prisutnost alkohola (Alcohol Denat) može iritirati duboko isušenu barijeru; preporučuje se primjena kod otpornije masne kože.')
  ),
  (
    'Biology AC Night-Peel',
    'A-Derma',
    'serum',
    ARRAY['acne-prone', 'sensitive'],
    'Inovativan piling na biljnoj bazi za korištenje tijekom noći. Formuliran s 99% sastojaka prirodnog podrijetla, kombinira organsku mliječnu kiselinu i Rhealba zobenu bazu za stimulaciju stanične obnove, borbu protiv prištića i ublažavanje zaostalih crvenih mrlja.',
    true,
    'https://www.soin-et-nature.com/en/27443-aderma-biology-ac-night-peel-serum-30-ml.html',
    'https://www.caretobeauty.com/us/a-derma-biology-ac-night-peel-new-skin-serum-30ml/',
    'retailer',
    '[]'::jsonb,
    jsonb_build_array('Certificirani organski proizvod unutar Biology linije, INCI verifikacija izvučena putem priznate farmaceutske platforme.')
  );
