UPDATE products
SET ingredients = '[
  "AQUA",
  "HYDROGENATED POLYISOBUTENE",
  "DIMETHICONE",
  "GLYCERIN",
  "BUTYROSPERMUM PARKII BUTTER / SHEA BUTTER",
  "PANTHENOL",
  "PROPANEDIOL",
  "BUTYLENE GLYCOL",
  "ALUMINUM STARCH OCTENYLSUCCINATE",
  "CETYL PEG/PPG-10/1 DIMETHICONE",
  "TRIHYDROXYSTEARIN",
  "ZINC GLUCONATE",
  "MADECASSOSIDE",
  "TRIBIOMA",
  "MANGANESE GLUCONATE",
  "SILICA",
  "ALUMINUM HYDROXIDE",
  "MAGNESIUM SULFATE",
  "DISODIUM EDTA",
  "COPPER GLUCONATE",
  "CAPRYLOYL GLYCINE",
  "CITRIC ACID",
  "ACETYLATED GLYCOL STEARATE",
  "POLYGLYCERYL-4 ISOSTEARATE",
  "TOCOPHEROL",
  "PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE",
  "CI 77891 / TITANIUM DIOXIDE"
]'::jsonb
WHERE name = 'Cicaplast Baume B5+';

UPDATE products
SET ingredients = '[
  "AQUA / WATER",
  "SODIUM LAURETH SULFATE",
  "PEG-8",
  "COCO-BETAINE",
  "HEXYLENE GLYCOL",
  "SODIUM CHLORIDE",
  "PEG-120 METHYL GLUCOSE DIOLEATE",
  "ZINC PCA",
  "SODIUM HYDROXIDE",
  "CAPRYLYL GLYCOL",
  "CITRIC ACID",
  "SODIUM BENZOATE",
  "PHENOXYETHANOL",
  "PARFUM / FRAGRANCE"
]'::jsonb
WHERE name = 'Effaclar Purifying Foaming Gel';

UPDATE products
SET ingredients = '[
  "AQUA / WATER",
  "CYCLOHEXASILOXANE",
  "ISONONYL ISONONANOATE",
  "PROPYLENE GLYCOL",
  "ISOHEXADECANE",
  "NIACINAMIDE",
  "PEG-100 STEARATE",
  "GLYCERYL STEARATE",
  "CETYL ALCOHOL",
  "AMMONIUM POLYACRYLOYLDIMETHYL TAURATE",
  "STEARYL ALCOHOL",
  "ISOBUTANE",
  "SODIUM HYDROXIDE",
  "MYRISTYL ALCOHOL",
  "CAPRYLOYL GLYCINE",
  "CAPRYLOYL SALICYLIC ACID",
  "CITRIC ACID",
  "XANTHAN GUM",
  "T-BUTYL ALCOHOL",
  "ACRYLONITRILE/METHYL METHACRYLATE/VINYLIDENE CHLORIDE COPOLYMER",
  "SALICYLIC ACID",
  "CHLORHEXIDINE DIGLUCONATE",
  "PIROCTONE OLAMINE",
  "PARFUM / FRAGRANCE"
]'::jsonb
WHERE name = 'Effaclar A.I.';

UPDATE products
SET ingredients = '[
  "AQUA / WATER",
  "PEG-7 CAPRYLIC/CAPRIC GLYCERIDES",
  "POLOXAMER 124",
  "POLOXAMER 184",
  "PEG-6 CAPRYLIC/CAPRIC GLYCERIDES",
  "GLYCERIN",
  "POLYSORBATE 80",
  "ZINC PCA",
  "SODIUM HYDROXIDE",
  "DISODIUM EDTA",
  "BHT",
  "MYRTRIMONIUM BROMIDE",
  "PARFUM / FRAGRANCE"
]'::jsonb
WHERE name = 'Effaclar Micellar Water';

UPDATE products
SET ingredients = '[
  "AQUA/ WATER",
  "ALCOHOL DENAT.",
  "GLYCERIN",
  "SODIUM CITRATE",
  "PROPYLENE GLYCOL",
  "DISODIUM EDTA",
  "CAPRYLOYL SALICYLIC ACID",
  "CITRIC ACID",
  "PARFUM/ FRAGRANCE"
]'::jsonb
WHERE name = 'Effaclar Astringent Lotion';
